### ISSUE TITLE
[DCU vGPU] Container cannot detect DCU device in virtualization mode

### ISSUE THREAD

**Issue by xrwang8** [Project-HAMi/HAMi#1776]
## Problem Description

When using HAMi DCU vGPU virtualization mode, the container cannot detect the DCU device after pod startup. Running any ROCm program (e.g., vllm) fails with `no ROCm-capable device is detected`. After manually sourcing `/opt/hygondriver/env.sh`, torch attempts to load Hygon driver libraries but encounters an `ncclCommRegister` undefined symbol error.

## Environment

- HAMi version: v2.7.1
- Device: Hygon DCU
- Container image:   image.sourcefind.cn:5000/dcu/admin/base/vllm:0.9.2-ubuntu22.04-dtk25.04.1-rc5-rocblas104381-0915-das1.6-py3.10-20250916-rc2
- Kubernetes: v1.28+

## Reproduction Steps

1. Create a pod with vGPU slice (e.g., `hygon.com/vgpu: 1`, memory less than full card)
2. Enter the container and run `vllm serve -h`
3. Error:
```
HIP error: no ROCm-capable device is detected
```
4. Manually run `source /opt/hygondriver/env.sh`, then run again:
```
ImportError: /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_hip.so: undefined symbol: ncclCommRegister
```

### Phase 1: Without sourcing env.sh
```
Could not open /var/log/hylog/.
terminate called after throwing an instance of 'c10::Error'
  what():  HIP error: no ROCm-capable device is detected
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Device-side assertions were explicitly omitted for this error check; the error probably arose while initializing the DSA handlers.
Exception raised from c10_hip_check_implementation at /home/pytorch/c10/hip/HIPException.cpp:45 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x99 (0x7f89a09756e9 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xe0 (0x7f89a091f9c8 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #2: c10::hip::c10_hip_check_implementation(int, char const*, char const*, int, bool) + 0x3a8 (0x7f89a5103f88 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_hip.so)
frame #3: c10::hip::HIPKernelLaunchRegistry::HIPKernelLaunchRegistry() + 0x9a (0x7f89a5102e2a in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_hip.so)
frame #4: c10::hip::HIPKernelLaunchRegistry::get_singleton_ref() + 0x44 (0x7f89a51030d4 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_hip.so)
frame #5: c10::hip::c10_hip_check_implementation(int, char const*, char const*, int, bool) + 0x45 (0x7f89a5103c25 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_hip.so)
frame #6: c10::hip::current_device() + 0x33 (0x7f89a51049b3 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10_hip.so)
frame #7: at::cuda::getCurrentDeviceProperties() + 0x9 (0x7f8962a67f59 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_hip.so)
frame #8: <unknown function> + 0x1231397 (0x7f87ad401397 in /usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so)
frame #9: <unknown function> + 0x647e (0x7f89a906547e in /lib64/ld-linux-x86-64.so.2)
frame #10: <unknown function> + 0x6568 (0x7f89a9065568 in /lib64/ld-linux-x86-64.so.2)
frame #11: _dl_catch_exception + 0xe5 (0x7f89a8e63af5 in /lib/x86_64-linux-gnu/libc.so.6)
frame #12: <unknown function> + 0xdff6 (0x7f89a906cff6 in /lib64/ld-linux-x86-64.so.2)
frame #13: _dl_catch_exception + 0x88 (0x7f89a8e63a98 in /lib/x86_64-linux-gnu/libc.so.6)
frame #14: <unknown function> + 0xe34e (0x7f89a906d34e in /lib64/ld-linux-x86-64.so.2)
frame #15: <unknown function> + 0x9063c (0x7f89a8d7f63c in /lib/x86_64-linux-gnu/libc.so.6)
frame #16: _dl_catch_exception + 0x88 (0x7f89a8e63a98 in /lib/x86_64-linux-gnu/libc.so.6)
frame #17: _dl_catch_error + 0x33 (0x7f89a8e63b63 in /lib/x86_64-linux-gnu/libc.so.6)
frame #18: <unknown function> + 0x9012e (0x7f89a8d7f12e in /lib/x86_64-linux-gnu/libc.so.6)
frame #19: dlopen + 0x48 (0x7f89a8d7f6c8 in /lib/x86_64-linux-gnu/libc.so.6)
frame #20: <unknown function> + 0x2820ff (0x564edf8ca0ff in /usr/bin/python3)
frame #21: <unknown function> + 0x280d17 (0x564edf8c8d17 in /usr/bin/python3)
frame #22: <unknown function> + 0x18b909 (0x564edf7d3909 in /usr/bin/python3)
frame #23: _PyEval_EvalFrameDefault + 0x65d6 (0x564edf7c3846 in /usr/bin/python3)
frame #24: _PyFunction_Vectorcall + 0x7c (0x564edf7d36ac in /usr/bin/python3)
frame #25: _PyEval_EvalFrameDefault + 0x5633 (0x564edf7c28a3 in /usr/bin/python3)
frame #26: _PyFunction_Vectorcall + 0x7c (0x564edf7d36ac in /usr/bin/python3)
frame #27: _PyEval_EvalFrameDefault + 0x807 (0x564edf7bda77 in /usr/bin/python3)
frame #28: _PyFunction_Vectorcall + 0x7c (0x564edf7d36ac in /usr/bin/python3)
frame #29: _PyEval_EvalFrameDefault + 0x6c0 (0x564edf7bd930 in /usr/bin/python3)
frame #30: _PyFunction_Vectorcall + 0x7c (0x564edf7d36ac in /usr/bin/python3)
frame #31: _PyEval_EvalFrameDefault + 0x6c0 (0x564edf7bd930 in /usr/bin/python3)
frame #32: _PyFunction_Vectorcall + 0x7c (0x564edf7d36ac in /usr/bin/python3)
frame #33: _PyEval_EvalFrameDefault + 0x6c0 (0x564edf7bd930 in /usr/bin/python3)
frame #34: _PyFunction_Vectorcall + 0x7c (0x564edf7d36ac in /usr/bin/python3)
frame #35: <unknown function> + 0x18ab09 (0x564edf7d2b09 in /usr/bin/python3)
frame #36: _PyObject_CallMethodIdObjArgs + 0xff (0x564edf8a792f in /usr/bin/python3)
frame #37: PyImport_ImportModuleLevelObject + 0x4b5 (0x564edf7e6585 in /usr/bin/python3)
frame #38: _PyEval_EvalFrameDefault + 0x3311 (0x564edf7c0581 in /usr/bin/python3)
frame #39: <unknown function> + 0x25a9d6 (0x564edf8a29d6 in /usr/bin/python3)
frame #40: PyEval_EvalCode + 0x86 (0x564edf8a28a6 in /usr/bin/python3)
frame #41: <unknown function> + 0x25ff4d (0x564edf8a7f4d in /usr/bin/python3)
frame #42: <unknown function> + 0x18b909 (0x564edf7d3909 in /usr/bin/python3)
frame #43: _PyEval_EvalFrameDefault + 0x65d6 (0x564edf7c3846 in /usr/bin/python3)
frame #44: _PyFunction_Vectorcall + 0x7c (0x564edf7d36ac in /usr/bin/python3)
frame #45: _PyEval_EvalFrameDefault + 0x5633 (0x564edf7c28a3 in /usr/bin/python3)
frame #46: _PyFunction_Vectorcall + 0x7c (0x564edf7d36ac in /usr/bin/python3)
frame #47: _PyEval_EvalFrameDefault + 0x807 (0x564edf7bda77 in /usr/bin/python3)
frame #48: _PyFunction_Vectorcall + 0x7c (0x564edf7d36ac in /usr/bin/python3)
frame #49: _PyEval_EvalFrameDefault + 0x6c0 (0x564edf7bd930 in /usr/bin/python3)
frame #50: _PyFunction_Vectorcall + 0x7c (0x564edf7d36ac in /usr/bin/python3)
frame #51: _PyEval_EvalFrameDefault + 0x6c0 (0x564edf7bd930 in /usr/bin/python3)
frame #52: _PyFunction_Vectorcall + 0x7c (0x564edf7d36ac in /usr/bin/python3)
frame #53: <unknown function> + 0x18ab09 (0x564edf7d2b09 in /usr/bin/python3)
frame #54: _PyObject_CallMethodIdObjArgs + 0xff (0x564edf8a792f in /usr/bin/python3)
frame #55: PyImport_ImportModuleLevelObject + 0x4b5 (0x564edf7e6585 in /usr/bin/python3)
frame #56: _PyEval_EvalFrameDefault + 0x3311 (0x564edf7c0581 in /usr/bin/python3)
frame #57: <unknown function> + 0x25a9d6 (0x564edf8a29d6 in /usr/bin/python3)
frame #58: PyEval_EvalCode + 0x86 (0x564edf8a28a6 in /usr/bin/python3)
frame #59: <unknown function> + 0x25ff4d (0x564edf8a7f4d in /usr/bin/python3)
frame #60: <unknown function> + 0x18b909 (0x564edf7d3909 in /usr/bin/python3)
frame #61: _PyEval_EvalFrameDefault + 0x65d6 (0x564edf7c3846 in /usr/bin/python3)
frame #62: _PyFunction_Vectorcall + 0x7c (0x564edf7d36ac in /usr/bin/python3)

Aborted (core dumped)
```

### Phase 2: After sourcing env.sh
```
root@hydcu-test-predictor-578f746ddd-rw2f7:/workspace# source /opt/hygondriver/env.sh
root@hydcu-test-predictor-578f746ddd-rw2f7:/workspace# vllm serve -h
Traceback (most recent call last):
  File "/usr/local/bin/vllm", line 3, in <module>
    from vllm.entrypoints.cli.main import main
  File "/usr/local/lib/python3.10/dist-packages/vllm/__init__.py", line 14, in <module>
    import vllm.env_override  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/vllm/env_override.py", line 5, in <module>
    import torch
  File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 368, in <module>
    from torch._C import *  # noqa: F403
ImportError: /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_hip.so: undefined symbol: ncclCommRegister
```

**Comment by xrwang8** [comment]
## Update: Issue Resolved with v2.4.1 Image

After testing, I found that using the image `harbor.sourcefind.cn:5443/dcu/admin/base/dcu-device-plugin:v2.4.1` resolves this problem — the container can correctly detect the DCU device in virtualization mode, and `vllm serve` runs without the `no ROCm-capable device is detected` error.

**Comment by wawa0210** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
When I use https://download.sourcefind.cn:65024/file/5/Kubernetes plug-in/dcu-device-plugin/k8s-dcu-plugin-hami.yaml to deploy, it can be used normally after specifying the image as harbor.sourcefind.cn:5443/dcu/admin/base/dcu-device-plugin:v2.4.1.

**Comment by xrwang8** [comment]
When deploying with https://download.sourcefind.cn:65024/file/5/Kubernetes插件/dcu-device-plugin/k8s-dcu-plugin-hami.yaml, using image harbor.sourcefind.cn:5443/dcu/admin/base/dcu-device-plugin:v2.4.1 works correctly for me.

**Comment by kinglong08** [comment]
When deploying using https://download.sourcefind.cn:65024/file/5/Kubernetes plug-in/dcu-device-plugin/k8s-dcu-plugin-hami.yaml, please pay attention to the support matrix of the driver box DTK, as shown in the figure

<img width="907" height="425" alt="Image" src="https://github.com/user-attachments/assets/4e70cd03-89a0-49cb-83c1-19dcc64c42e4" />
