### ISSUE TITLE
vgpu安装成功后 无法使用cuda

### ISSUE THREAD

**Issue by su161021** [Project-HAMi/HAMi#662]
python test_pytorch.py 
[HAMI-core Msg(30:140387636202368:libvgpu.c:836)]: Initializing.....
[HAMI-core Msg(30:140387636202368:libvgpu.c:855)]: Initialized
[HAMI-core ERROR (pid:30 thread=140382094939712 allocator.c:53)]: Device 0 OOM 3171158016 / 3145728000
Traceback (most recent call last):
  File "/data/test_pytorch.py", line 69, in <module>
    run_gpu_stress_test()  # 启动 GPU 持续计算任务
    ^^^^^^^^^^^^^^^^^^^^^
  File "/data/test_pytorch.py", line 61, in run_gpu_stress_test
    loss = train_one_epoch()  # 每次训练都执行一次
           ^^^^^^^^^^^^^^^^^
  File "/data/test_pytorch.py", line 51, in train_one_epoch
    loss.backward()  # 反向传播
    ^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/_tensor.py", line 581, in backward
    torch.autograd.backward(
  File "/opt/conda/lib/python3.11/site-packages/torch/autograd/__init__.py", line 347, in backward
    _engine_run_backward(
  File "/opt/conda/lib/python3.11/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: unrecognized error code
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
![Snipaste_2024-12-01_00-05-16](https://github.com/user-attachments/assets/1ead39d7-1edf-4fb8-b46f-6ab74105fe74)
有大佬遇到这个问题吗，插件都是正常的 pod也能起来，同样的程序 同样的经常使用docker run就能跑，vgpu以后就报错了

**Comment by Radical-3** [comment]
请问您可以成功创建申请了gpu的pod吗，我部署HAMi之后，创建pod报错，想问一下您是怎么部署的。

**Comment by su161021** [comment]
> 请问您可以成功创建申请了gpu的pod吗，之后我配置了HAMi，创建pod报错，想问一下您是怎么配置的。

我可以正常安装 使用master分支版本命令行安装就行

**Comment by su161021** [comment]
> 请问您可以成功创建申请了gpu的pod吗，之后我配置了HAMi，创建pod报错，想问一下您是怎么配置的。

我可以正常申请gpu pod ，就是在pod里使用gpu的时候会报cuda错误，我使用的是master分支安装的，您可以参考master分支安装教程

**Comment by Radical-3** [comment]
方便加一下wx吗，我想向您询问一下具体情况 @su161021，我的wx号是a2973051203

**Comment by su161021** [comment]
> @su161021 你这个程序要申请 3171158016，但是这个 Pod 最多就 3145728000（3000MiB），被 HAMi-core 限了，返回了 OOM，所以你 Pod 的声明把 nvidia.com/gpumem 稍微调大一点试试

感谢指教，调大了 确实好了，不过我看算力好像没有限制住，只起一个pod的话 nvidia.com/gpucores: 30，pod里面运行程序还是可以使用到100的算力，这个您有遇到过吗

**Comment by su161021** [comment]
> 方便加一下wx吗，我想向您询问一下具体情况 @su161021，我的wx号是a2973051203

加你了

**Comment by Nimbus318** [comment]
@su161021 你的问题在 issue 的置顶栏里面可以找到 [FAQ](https://github.com/Project-HAMi/HAMi/issues/646)，里面有一个[中文版的链接](https://v6eky86feo.feishu.cn/wiki/ViC8wFcItiCCzjkx2c3cgXMhnwh)，这个回答我还没有完善所以在 Draft 里

![CleanShot 2024-12-02 at 12 22 19@2x](https://github.com/user-attachments/assets/fd7ce044-6ceb-4ba0-be22-63e1062c88b8)

也就是说如果现在单卡上就这一个 Pod 在使用算力，可以用到 100 的算力，是符合预期的

**Comment by su161021** [comment]
> @su161021 你的问题在 issue 的置顶栏里面可以找到 [FAQ](https://github.com/Project-HAMi/HAMi/issues/646)，里面有一个[中文版的链接](https://v6eky86feo.feishu.cn/wiki/ViC8wFcItiCCzjkx2c3cgXMhnwh)，这个回答我还没有完善所以在 Draft 里
> 
> ![CleanShot 2024-12-02 at 12 22 19@2x](https://private-user-images.githubusercontent.com/136771156/391409735-fd7ce044-6ceb-4ba0-be22-63e1062c88b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMTM5MjgsIm5iZiI6MTczMzExMzYyOCwicGF0aCI6Ii8xMzY3NzExNTYvMzkxNDA5NzM1LWZkN2NlMDQ0LTZjZWItNGJhMC1iZTIyLTYzZTEwNjJjODhiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQwNDI3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Zjg4ODhjNjg0NDk5MzdmNzJkNGE4Y2U2MDA1MTljOTdkOTE3YzY1NjM1YTQ1ZWRjNTIxMGNmMjk3Yjg3ZGRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JYpFeC9bQ3XSqKJ9Moz5ODumDH9dxalhfeEQOTK_0NU)
> 
> 也就是说如果现在单卡上就这一个 Pod 在使用算力，可以用到 100 的算力，是符合预期的

感谢大佬回复 设置完以后看着是限制住了

**Comment by 1475439119** [comment]
> [@su161021](https://github.com/su161021) 你这个程序要申请 3171158016，但是这个 Pod 最多就 3145728000（3000MiB），被 HAMi-core 限了，返回了 OOM，所以你 Pod 的声明把 nvidia.com/gpumem 稍微调大一点试试

我遇到的问题是，同样的模型，之前8g显存就能正常启动，后来改了下代码，还是1.5b的模型，20g显存都报OOM，改成80G都报OOM，不知道hami出什么问题了，那张显卡nvidia-smi查看，显存用了0
